trigger:
- none

pool: selfhosted-pool-01
variables:
- group: VM_Credentials
  
stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:  
          - task: TerraformTaskV4@4
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              backendServiceArm: 'acr-aks-spn'
              backendAzureRmResourceGroupName: 'devops-test-rg'
              backendAzureRmStorageAccountName: 'teststorage45678'
              backendAzureRmContainerName: 'stfstatefile'
              backendAzureRmKey: 'dev.terraform.tfstate' 
          - task: TerraformTaskV4@4
            displayName: terraform validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
  - stage: tfapply
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        continueOnError: false
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              backendServiceArm: 'acr-aks-spn'
              backendAzureRmResourceGroupName: 'devops-test-rg'
              backendAzureRmStorageAccountName: 'teststorage45678'
              backendAzureRmContainerName: 'stfstatefile'
              backendAzureRmKey: 'dev.terraform.tfstate'
          - task: Bash@3 
            inputs:
              targetType: 'inline'
              script: 'terraform state list'
          
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'acr-aks-spn'
          #     scriptType: 'batch'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: 'terraform force-unlock baafeaf0-53d9-f59d-1197-7bd9c313def8'
          #     workingDirectory: 'codebase1/Codebase/terraform_machine'
          - task: TerraformTaskV4@4
            displayName: terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              environmentServiceNameAzureRM: 'acr-aks-spn'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'acr-aks-spn'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'terraform state list'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
          - task: TerraformTaskV4@4
            displayName: terrfaorm apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              environmentServiceNameAzureRM: 'acr-aks-spn'
            
          
          
          