trigger:
- none

pool: selfhosted-pool-01
# variables:
# - group: VM_Credentials
  
stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:  
          - task: TerraformTaskV4@4
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              backendServiceArm: 'acr-aks-spn'
              backendAzureRmResourceGroupName: 'devops-test-rg'
              backendAzureRmStorageAccountName: 'teststorage45678'
              backendAzureRmContainerName: 'stfstatefile'
              backendAzureRmKey: 'dev.terraform.tfstate' 
          - task: TerraformTaskV4@4
            displayName: terraform validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
  - stage: tfapply
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        continueOnError: false
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              backendServiceArm: 'acr-aks-spn'
              backendAzureRmResourceGroupName: 'devops-test-rg'
              backendAzureRmStorageAccountName: 'teststorage45678'
              backendAzureRmContainerName: 'stfstatefile'
              backendAzureRmKey: 'dev.terraform.tfstate'
          - task: Bash@3 
            displayName: Terraform State list
            inputs:
              targetType: 'inline'
              script: 'terraform state list'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
          - task: Bash@3 
            displayName: Terraform State refresh
            inputs:
              targetType: 'inline'
              script: |
                terraform refresh
              workingDirectory: 'codebase1/Codebase/terraform_machine'
          # - task: Bash@3 
          #   displayName: Unlock Terraform State
          #   inputs:
          #     targetType: 'inline'
          #     script: |
          #       echo "yes" | terraform force-unlock 12266fe7-41fb-3480-703d-dff39023834f
          #     workingDirectory: 'codebase1/Codebase/terraform_machine'
          - task: TerraformTaskV4@4
            displayName: terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              environmentServiceNameAzureRM: 'acr-aks-spn'
          - task: TerraformTaskV4@4
            displayName: terrfaorm apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              environmentServiceNameAzureRM: 'acr-aks-spn'
            
          
          
          