trigger:
- main

pool: selfhosted-pool-01

# variables:
  
stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          # - task: TerraformInstaller@1
          #   displayName: tfinstall
          #   inputs:
          #     terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'acr-aks-spn'
              backendAzureRmResourceGroupName: 'devops-test-rg'
              backendAzureRmStorageAccountName: 'teststorage45678'
              backendAzureRmContainerName: 'stfstatefile'
              backendAzureRmKey: 'dev.terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: tf validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTaskV4@4
            displayName: tf plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'acr-aks-spn'
          