trigger:
- none

pool: selfhosted-pool-01

# variables:
  
stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              backendServiceArm: 'acr-aks-spn'
              backendAzureRmResourceGroupName: 'devops-test-rg'
              backendAzureRmStorageAccountName: 'teststorage45678'
              backendAzureRmContainerName: 'stfstatefile'
              backendAzureRmKey: 'dev.terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: terraform validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
            
          - task: TerraformTaskV4@4
            displayName: tf plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              environmentServiceNameAzureRM: 'acr-aks-spn'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: 'codebase1/Codebase/terraform_machine'
              environmentServiceNameAzureRM: 'acr-aks-spn'
          # - task: TerraformTaskV4@4
          #   inputs:
          #     provider: 'azurerm'
          #     command: 'destroy'
          #     workingDirectory: 'codebase1/Codebase/terraform_machine'
          #     environmentServiceNameAzureRM: 'acr-aks-spn'
          
          
          